### ISSUE TITLE
Error when build iknow Domain

### ISSUE THREAD

**Issue by isc-ddo** [bdeboe/isc-iknow-covid#2]
@bdeboe
I run the sample code with my existing instance,
After I download the .tar.gz file, I cannot build the domain. Could you help me out?
![image](https://user-images.githubusercontent.com/42380058/78296261-634faa00-74fb-11ea-8742-776afaab4fc1.png)

**Comment by bdeboe** [comment]
That means something went wrong downloading the dataset. Can you verify whether anything is in the Research.FullDocument table? Likely nothing, otherwise the "Downloading..." log line would have been followed by something else. You can also try to see which error is returned from that `Download()` call.
I've heard someone running into issues working with an internal release where the default SSL config is not available. Maybe you can take a look at the ´Download()` method and check if changing this to an existing SSL config helps?

**Comment by bdeboe** [comment]
after direct consultation, this seems to have been resolved upon trying from a clean slate 👍 
Thanks for testing @DuongDo-Intersystems !
